version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: app_postgres
    environment:
      POSTGRES_USER: nextdatabase
      POSTGRES_PASSWORD: nextdatabase
      POSTGRES_DB: nextdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
